config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  resources :items
  root 'contacts#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :phones, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  accepts_nested_attributes_for :phones, reject_if: lambda { |a| a[:number].blank? }, allow_destroy: true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts, dependent: :restrict_with_error
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :authenticate_user!

  load_and_authorize_resource unless: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end


  def set_locale
    session[:locale] = params[:locale] || session[:locale] || I18n.default_locale
    I18n.locale = session[:locale]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.paginate(page: params[:page], per_page: 1)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :birthday, :avatar, phones_attributes: [:number, :_destroy, :id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) +
        link_to(name, "javascript:void(0)", onclick: "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, "javascript:void(0)", onclick: h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :avatar, as: :file %>
    <%= f.input :name %>
    <%= f.input :birthday %>
  </div>

  <div>
    <%= f.simple_fields_for :phones do |builder| %>
      <%= render "phone_fields", f: builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Phone", f, :phones %></p>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/contacts/_phone_fields.html.erb
<p class="fields">
  <%= f.label :number, "phone number" %>
  <%= f.text_field :number %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/contacts/edit.html.erb
<h1><%= t('editing', name: t('contact.title', count: 1)) %></h1>

<%= render 'form' %>

<%= link_to t('show'), @contact, class: 'btn btn-info', role: :button %>
<%= link_to t('index'), contacts_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/contacts/index.html.erb
<h1><%= t('listing', name: t('contact.title', count: 2)) %></h1>

<table class="table table-striped table-hover table-sm">
 <thead>
   <tr>
     <th scope="col"><%= t('contact.name') %></th>
     <th scope="col"><%= t('contact.birthday') %></th>
     <th scope="col"><%= t('actions') %></th>
   </tr>
 </thead>

 <tbody>
   <% @contacts.each do |contact| %>
     <tr>
       <td><%= contact.name %></td>
       <td><%= contact.birthday %></td>
       <td>
         <div class="btn-group btn-group-sm" role="group">
           <%= link_to t('show'), contact, class: 'btn btn-info', role: :button %>
           <%= link_to t('edit'), edit_contact_path(contact), class: 'btn btn-success', role: :button %>
           <%= link_to t('destroy'), contact, method: :delete, data: { confirm: t('confirm_destroy') }, class: 'btn btn-danger', role: :button %>
         </div>
       </td>
     </tr>
   <% end %>
 </tbody>
</table>
<%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to t('new', name: t('contact.title', count: 1)), new_contact_path, class: 'btn btn-primary', role: :button %>

app/views/contacts/new.html.erb
<h1><%= t('new', name: t('contact.title', count: 1)) %></h1>

<%= render 'form' %>

<%= link_to t('index'), contacts_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/contacts/show.html.erb
<h1><%= t('listing', name: t('contact.title', count: 1)) %></h1>

<%= image_tag(@contact.avatar_url, class: 'rounded mx-auto d-block') if @contact.avatar? %>

<table class="table table-striped table-hover">

 <tr>
   <th scope="row"><%= t('contact.name') %>:</th>
   <td><%= @contact.name %></td>
 </tr>
 <tr>
   <th scope="row"><%= t('contact.birthday') %>:</th>
   <td><%= @contact.birthday %></td>
 </tr>

  <p>
    <strong>Phones</strong>
    <% @contact.phones.each do |phone| %>
    <p>
      <%= phone.number %>
    </p>
  <% end %>
  </p>
</table>

<%= link_to t('edit'), edit_contact_path(@contact), class: 'btn btn-primary', role: :button %>
<%= link_to t('index'), contacts_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/home/index.html.erb
<h1>My home page</h1>
<p>Paragraph</p>

app/views/items/_form.html.erb
<div class="form-group">
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :done %>
    <%= form.check_box :done %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'btn btn-primary' %>
    <%= form.submit "clean", :type => 'reset', :class => 'btn btn-warning'%>
  </div>
<% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item, class: 'btn btn-info' %> |
<%= link_to 'Back', items_path, class: 'btn btn-primary' %>

app/views/items/index.html.erb
<h1>Items</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Done</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.done %></td>
        <td><%= link_to 'Show', item, class: 'btn btn-info' %>
        <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-success' %>
        <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path, class: 'btn btn-primary' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @item.done %>
</p>

<%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-success' %> |
<%= link_to 'Back', items_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'pt-BR', root_path(locale: 'pt-BR'), class: 'nav-item nav-link' %>
    <%= link_to 'en', root_path(locale: 'en'), class: 'nav-item nav-link' %>
    <%= link_to t('contacts'), root_path, class: 'navbar-brand' %> <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-item nav-link') %>
    <% end %>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav">
        <%= link_to 'Any link', '#', class: 'nav-item nav-link' %>
      </div>
    </div>
  </nav>

  <main class="container" role="main">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
  </main>
  </body>
</html>